# Generated by Django 5.2.8 on 2025-11-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmi', models.FloatField()),
                ('waist_cm', models.FloatField()),
                ('sex_assigned_at_birth', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('physical_activity', models.BooleanField()),
                ('daily_fruit_veg', models.BooleanField()),
                ('bp_medication', models.BooleanField()),
                ('high_blood_sugar_history', models.BooleanField()),
                ('family_history', models.CharField(choices=[('none', 'No Family History'), ('extended', '2nd-degree Relative'), ('close', '1st-degree Relative')], max_length=10)),
                ('fbs', models.FloatField()),
                ('total_score', models.IntegerField()),
                ('risk_category', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
