# Generated by Django 5.2.8 on 2025-11-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesrecord',
            name='diastolic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetesrecord',
            name='pulse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetesrecord',
            name='systolic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesrecord',
            name='family_history',
            field=models.CharField(blank=True, choices=[('zero', 'No Family History'), ('second', '2nd-degree Relative'), ('first', '1st-degree Relative')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesrecord',
            name='physical_activity',
            field=models.CharField(blank=True, choices=[('vigorous', 'Vigorous exercise / strenuous work'), ('moderate', 'Moderate exercise at work/home'), ('mild', 'Mild exercise at work/home'), ('sedentary', 'No exercise / sedentary lifestyle')], max_length=10, null=True),
        ),
    ]
